import csv
import json
import os

_AUG_DIR = os.path.join(os.path.dirname(__file__), "..", "county_data", "augmented_data")


def parse_county_data(filepath, state_fips):
    """
    Parse county demographics for a single state from a CSV file.

    Accepts flexible column naming for FIPS, county name, state name, population,
    latitude, and longitude. Keeps only rows belonging to the requested state FIPS
    prefix and writes the result to
    `county_data/augmented_data/county_data_<state_fips>.json`.

    Returns:
        dict[str, dict[str, object]]: county FIPS to county metadata.
    """
    state_fips = str(state_fips).zfill(2)[:2]
    rows = {}
    with open(filepath, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        fields = {h.lower().strip(): h for h in reader.fieldnames or []}

        def col(*names):
            # Resolve the first available header alias from the CSV.
            for n in names:
                if n in fields:
                    return fields[n]
            return None

        fips_col = col("fips")
        county_name_col = col("name")
        state_name_col = col("state")
        population_col = col("population")
        lat_col = col("lat")
        lon_col = col("lon")
        if not all([fips_col, county_name_col, state_name_col, population_col, lat_col, lon_col]):
            raise ValueError(
                "CSV must include FIPS, name, state, population, lat, lon (flexible column names)."
            )

        for row in reader:
            county_fips = str(row[fips_col]).strip().replace('"', "")
            if len(county_fips) < 5:
                county_fips = county_fips.zfill(5)
            if not county_fips.startswith(state_fips):
                continue
            county_name = row[county_name_col].strip()
            state_name = row[state_name_col].strip()
            try:
                population = int(float(row[population_col]))
            except (TypeError, ValueError):
                # Skip rows with non-numeric population values.
                continue
            try:
                lat = float(row[lat_col])
                lon = float(row[lon_col])
            except (TypeError, ValueError):
                # Skip rows with invalid coordinate values.
                continue
            entry = {
                "name": county_name,
                "state": state_name,
                "population": population,
                "lat": lat,
                "lon": lon,
            }
            rows[county_fips] = entry

    os.makedirs(_AUG_DIR, exist_ok=True)
    out_path = os.path.join(_AUG_DIR, f"county_data_{state_fips}.json")
    with open(out_path, "w", encoding="utf-8") as out:
        json.dump(rows, out, indent=2)
    return rows


def load_county_data(state_fips):
    """
    Load the cached county demographics generated by `parse_county_data`.

    Args:
        state_fips: State FIPS code (string/int); normalized to 2 digits.

    Returns:
        dict[str, dict[str, object]]: county FIPS to county metadata.
    """
    state_fips = str(state_fips).zfill(2)[:2]
    path = os.path.join(_AUG_DIR, f"county_data_{state_fips}.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)
