import json
import os
from collections import defaultdict

_AUG_DIR = os.path.join(os.path.dirname(__file__), "..", "county_data", "augmented_data")


def _iter_adjacency_rows(filepath):
    """
    Yield (county_fips, neighbor_fips) pairs from Census adjacency text rows.

    The source file may omit the county columns on continuation rows; in that case,
    reuse the most recent county FIPS encountered on a full row.
    """
    last_county_fips = None
    with open(filepath, encoding="utf-8") as f:
        next(f)  # Skip header line.
        for line in f:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            parts = line.split("|")
            if len(parts) < 4:
                continue
            # Continuation rows have an empty county-name column.
            if not parts[0].strip() and last_county_fips is not None:
                county_fips = last_county_fips
                neighbor_fips = parts[2].strip()
            else:
                county_fips = parts[1].strip()
                neighbor_fips = parts[3].strip()
                last_county_fips = county_fips
            yield county_fips, neighbor_fips


def parse_adjacency(filepath, state_fips):
    """
    Parse Census county adjacency rows for a single state.

    Keeps only county-to-county edges where both county FIPS values start with the
    requested 2-digit state code. Builds an undirected adjacency map and writes it
    to `county_data/augmented_data/adjacency_<state_fips>.json`.

    Returns:
        dict[str, list[str]]: county FIPS to sorted list of neighboring county FIPS.
    """
    state_fips = str(state_fips).zfill(2)[:2]
    neighbors = defaultdict(set)
    for county_fips, neighbor_fips in _iter_adjacency_rows(filepath):
        if not (county_fips.startswith(state_fips) and neighbor_fips.startswith(state_fips)):
            continue
        if county_fips == neighbor_fips:
            continue
        neighbors[county_fips].add(neighbor_fips)
        neighbors[neighbor_fips].add(county_fips)

    adjacency_map = {county: sorted(neighbor_set) for county, neighbor_set in sorted(neighbors.items())}
    os.makedirs(_AUG_DIR, exist_ok=True)
    out_path = os.path.join(_AUG_DIR, f"adjacency_{state_fips}.json")
    with open(out_path, "w", encoding="utf-8") as out:
        json.dump(adjacency_map, out, indent=2)
    return adjacency_map


def load_adjacency(state_fips):
    """
    Load the cached adjacency map generated by `parse_adjacency`.

    Args:
        state_fips: State FIPS code (string/int); normalized to 2 digits.

    Returns:
        dict[str, list[str]]: county FIPS to sorted neighboring county FIPS.
    """
    state_fips = str(state_fips).zfill(2)[:2]
    path = os.path.join(_AUG_DIR, f"adjacency_{state_fips}.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)
